"""
Django settings for kbus_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
import environ
import dj_database_url


env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure apps like `transport` (located at BASE_DIR/transport) are importable
# even if the process is started from BASE_DIR/kbus_project.
_base_dir_str = str(BASE_DIR)
if _base_dir_str not in sys.path:
    sys.path.insert(0, _base_dir_str)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Render sets env vars; default to safe production behavior.
DEBUG = env.bool('DEBUG', default=False)

def _unique_hosts(values):
    seen = set()
    out = []
    for v in values:
        v = (v or '').strip()
        if not v:
            continue
        if v in seen:
            continue
        seen.add(v)
        out.append(v)
    return out


# Allow Render hostnames + local dev by default.
# You can override via env var: ALLOWED_HOSTS=kbus-1.onrender.com,custom.domain
_default_hosts = ['kbus-1.onrender.com', 'localhost', '127.0.0.1', '.onrender.com']

# Render provides this env var at runtime; include it automatically.
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host:
    _default_hosts.append(_render_host)

# Needed for Django test client and some health checks
_default_hosts.append('testserver')

ALLOWED_HOSTS = _unique_hosts(env.list('ALLOWED_HOSTS', default=_default_hosts))

# If you serve the site over HTTPS behind a proxy (Render), Django needs this
# for correct scheme detection (affects CSRF/origin checks).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# For HTTPS POSTs (like login) on Render/custom domains.
_default_csrf = ['https://kbus-1.onrender.com', 'https://*.onrender.com']
if _render_host:
    _default_csrf.append('https://' + _render_host)

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=_unique_hosts(_default_csrf))

AUTH_USER_MODEL = 'transport.User'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    
    'transport',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kbus_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kbus_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


_database_url = os.environ.get('DATABASE_URL')
if not _database_url:
    _database_url = env('DATABASE_URL', default=None)

if _database_url:
    # Render (and most PaaS) provides DATABASE_URL for Postgres.
    DATABASES = {
        'default': dj_database_url.parse(
            _database_url,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
    try:
        _engine = (DATABASES.get('default') or {}).get('ENGINE')
        if _engine and 'postgres' in str(_engine):
            DATABASES['default'].setdefault('OPTIONS', {})
            # Fail fast instead of hanging the request (e.g., during login).
            DATABASES['default']['OPTIONS'].setdefault('connect_timeout', 10)
    except Exception:
        pass
else:
    # Fallback for local development.
    _engine = env('ENGINE', default='django.db.backends.sqlite3')
    if _engine == 'django.db.backends.sqlite3':
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': _engine,
                'NAME': env('NAME', default=''),
                'USER': env('USER', default=''),
                'PASSWORD': env('PASSWORD', default=''),
                'HOST': env('HOST', default=''),
                'PORT': env('PORT', default='5432'),
            }
        }



REST_FRAMEWORK = {
    
    'DEFAULT_AUTHENTICATION_CLASSES': (
       
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

  
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=3000),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),



    "AUTH_HEADER_TYPES": ("Bearer",),
    
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Display timezone for templates/admin. Datetimes are still stored in UTC when USE_TZ=True.
TIME_ZONE = env('TIME_ZONE', default='Asia/Kolkata')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'
# App-provided static files (e.g. transport/static) are discovered automatically
# via AppDirectoriesFinder; adding them again here causes collectstatic conflicts.
STATICFILES_DIRS = []
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
