# Generated by Django 6.0.2 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
