# Generated by Django 6.0.2 on 2026-02-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_ticket_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('passenger', 'Passenger'), ('driver', 'Driver')], max_length=20),
        ),
    ]
