# Generated by Copilot on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0003_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverRegistration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("driver_name", models.CharField(max_length=150)),
                ("bus_otp", models.CharField(max_length=5)),
                ("role", models.CharField(default="driver", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
